language: python
python:
    - 3.6
    - 3.5
    - 2.7
sudo: false
install:
    - pip install -U pip
    - pip install -U --upgrade-strategy eager ".[test]" coveralls
    - pip freeze
script:
    - pytest --cov=traittypes traittypes
after_success:
    - coveralls
